### ISSUE TITLE
Solve the mystery of why only some DEA Tools modules render in the User Guide... 🕵

### ISSUE THREAD

**Issue by treefern** [GeoscienceAustralia/dea-notebooks#1021]
The User Guide renders our DEA Tools Python package here:
https://docs.dea.ga.gov.au/notebooks/Tools/index.html

But this list only includes some of the DEA Tools modules (https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop/Tools/dea_tools), not all. **Why are some missing?**

Last time we looked into this, the theory was it was something to do with this: https://github.com/GeoscienceAustralia/dea-docs/blob/master/conf.py#L30-L89

**Comment by BexDunn** [comment]
Nathan - 19/07 - non-trivial Sphinx bug?

**Comment by omad** [comment]
Fixed. The theory was correct, but the case was incorrect. I needed to change `Shapely` to `shapely` and they all appeared, that list is python module names, not package names. The Sphinx build errors pointed the way.

https://github.com/GeoscienceAustralia/dea-docs/blame/master/conf.py#L84

**Comment by robbibt** [comment]
No way! The amount of time I've spent trying to solve this issue over the past year or two... such a simple fix too. Thanks @omad, this is awesome - being able to easily share our function documentation with users will be fantastic.
