### ISSUE TITLE
Link to datacube.Datacube.load readthedocs broken

### ISSUE THREAD

**Issue by LaurenSchenk1** [GeoscienceAustralia/dea-notebooks#1058]
**Describe the bug/issue**
Link to datacube.Datacube.load docs leads to 404 error. 

https://datacube-core.readthedocs.io/en/latest/dev/api/generate/datacube.Datacube.load.html

**Steps to reproduce**
1. Go to https://github.com/GeoscienceAustralia/dea-notebooks/blob/b13f020f8a41c30bc1bb4120ce492098a25a2bfa/Tools/dea_tools/datahandling.py#L239
2. In the load_ard() function, line 239 for broken link
3. Open broken link

**Expected behaviour**
Should lead to this page: https://datacube-core.readthedocs.io/en/latest/api/indexed-data/generate/datacube.Datacube.load.html?highlight=datacube.load

**Comment by robbibt** [comment]
Great catch! Have raised a PR here to fix it: #1061

**Comment by LaurenSchenk1** [comment]
Thanks @robbibt!
