### ISSUE TITLE
Explain the difference between load_ard and dc.load in a notebook

### ISSUE THREAD

**Issue by LaurenSchenk1** [GeoscienceAustralia/dea-notebooks#1059]
**Describe the bug/issue**
Explain the difference between load_ard and dc.load in a notebook

**Comment by robbibt** [comment]
Hey @LaurenSchenk1, we have this notebook here: https://docs.dea.ga.gov.au/notebooks/How_to_guides/Using_load_ard.html

Have a look and see if it covers what you were after - we might want to add some extra specific info about how they differ, or perhaps also update the Loading data notebook here:
https://docs.dea.ga.gov.au/notebooks/Beginners_guide/04_Loading_data.html

**Comment by LaurenSchenk1** [comment]
Hi @robbibt, I think it was really good that you added that extra little bit in one of the Beginner Guides to introduce people to the difference between the two. 
Thanks for your help!
