### ISSUE TITLE
Update GettingStarted notebooks to use DEA functions instead of hardcoding

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#109]
Currently some of the example notebooks (e.g. "GettingStartedWithLandsat5-6-7") use older versions of the DEA functions that have been hard-coded into the notebook. 

Instead, we should use the existing DEA module functions.

**Comment by CEKrause** [comment]
@robbibt Can you provide an example? I don't quite know what you mean...
