### ISSUE TITLE
Fix Waterbodies dataset notebook to correctly identify bit flags

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#1099]
https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/DEA_products/DEA_Water_Observations.ipynb 

Update table to correctly represent how bitflags are calculated, and:

Check that the bit flags in the table are correct for collection 3

**Comment by BexDunn** [comment]
the DEA Waterbodies dataset notebook explanation of bitflags is inverted in the way the numbers are explained, and we need to check the values for the flags are correctly identified for collection 3.

**Comment by robbibt** [comment]
Done!
