### ISSUE TITLE
WIT flowchart is rendering long and skinny in sphinx docs

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#1106]
WIT flowchart is rendering long and skinny in sphinx docs.

Docs rendering is showing up different to notebook rendering. The html controlling the size of the image in the notebook needs adjusting so the image is readable in the docs.

**Steps to reproduce**
1. Go to https://docs.dea.ga.gov.au/notebooks/DEA_products/DEA_Wetlands_Insight_Tool.html 
![witrender](https://github.com/GeoscienceAustralia/dea-notebooks/assets/20038594/ab97c50d-9540-4fac-a8da-a1db0185d830)

**Expected behaviour**
![image](https://github.com/GeoscienceAustralia/dea-notebooks/assets/20038594/24a93c29-1b0f-4719-9a24-036e66de679d)

**Environment information**
 [DEA Sandbox](https://docs.dea.ga.gov.au/setup/sandbox.html) and Chrome to view the docs

**Comment by robbibt** [comment]
Oh that's weird. Could try resizing the image file itself to the right width, then just rendering it using plain markdown? e.g.
```
![](*.jpg)
```

**Comment by BexDunn** [comment]
Here's a question - do we know what the 'right width' is for a jupyter notebook, given different screen rendering and sizes? A quick search of stackexchange suggests using the `Image` module from `IPython.display` could be a good option https://stackoverflow.com/questions/41598916/resize-the-image-in-jupyter-notebook-using-markdown -however it's an old post, so I'm not sure what the most recent solution would be..

**Comment by robbibt** [comment]
I think if you use the markdown approach it will just scale it correctly by default - I don't think I've needed to specify a specific width/height using that method in the past. E.g. just looking at a notebook like this where we have a few images, which all seem to be rendering OK to the width of the notebook (the table is worse though!)

https://docs.dea.ga.gov.au/notebooks/Beginners_guide/02_DEA.html

**Comment by BexDunn** [comment]
closed by #1222 and #1230
