### ISSUE TITLE
Replace all usages of `xarray.open_rasterio()`

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/dea-notebooks#1108]
The `xarray.open_rasterio()` function was removed from xarray version 2023.04.

It should be replaced with `xarray.open_dataset(..., engine="rasterio")` which will defer to [rioxarray](https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html).

**Comment by robbibt** [comment]
Neat, this sounds like a great job for the upcoming innovation day hack @BexDunn @erialC-P
