### ISSUE TITLE
dea-tools pypi package

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-notebooks#1114]
**Describe the bug/issue**
Publish dea-tools with changes as a PyPI package for other environments running dea-notebooks.

**Steps to reproduce**
Steps to reproduce the behaviour. For example:
dea-tools is installed from PyPI in CSIRO EASI sandbox images. Some of the current notebooks developed in dea-sandbox are not portable since the dea-tools module has not yet been published in PyPI. It would be great to have a fresh release with the new changes.

**Expected behaviour**
dea-tools with latest changes can be installed via `pip install`

**Environment information**
What datacube environment are you using? i.e. [CSIRO EASI-Hub](https://hub.csiro.easi-eo.solutions/)

**Comment by robbibt** [comment]
Hey @whatnick, we have DEA Tools published on PyPI here: https://pypi.org/project/dea-tools/#history

We're long overdue for an official release, but you should be able to load the latest dev versions to get the most recent changes. 

If you had any feedback on any issues you have with installing the package outside of the Sandbox, I'd love to hear it - I don't have a good idea of how portable it is, and would love to make it easier for external users to access our tools.

**Comment by robbibt** [comment]
E.g. one suggested change to make `dea-tools` easier to install here: https://github.com/GeoscienceAustralia/dea-notebooks/issues/1115

**Comment by whatnick** [comment]
We will try out the dev release from PyPI in EASI containers. Perhaps a docs note to make the dev package easier to discover under DEA Tools folder.

**Comment by omad** [comment]
Oh wow, we definitely need newer non-dev releases!

**Comment by robbibt** [comment]
@omad Yeah totally! Part of why we've dragged our feet with this is that we don't really have a good idea of whether the package is actually easy to install and use by externals. I'd hate for us to announce a big release with lots of new features, and then have users be unable to actually install it on their systems... that would be a bad look (which seems to have happened with USGS recently sadly).

Unfortunately I just don't have the skillset to test this out in a way that would simulate a "clean" non-Sandbox environment! 

Either way though, I think the plan is to hopefully get a release out at the end of tomorrow's DEA Notebooks innovation day hack. 🤞  And then hopefully much more frequently from that point on!

**Comment by robbibt** [comment]
We have pushed a 0.3.0 update to DEA Tools. :)
