### ISSUE TITLE
Small typo in DEA Mangroves notebook

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#1136]
**Describe the bug/issue**
"definitons" instead of "definitions":
https://docs.dea.ga.gov.au/notebooks/DEA_products/DEA_Mangroves.html#View-the-DEA-Mangroves-class-values-and-definitons

Can probably also remove the capitalisation here:
https://docs.dea.ga.gov.au/notebooks/DEA_products/DEA_Mangroves.html#Plotting-Data

**Comment by erialC-P** [comment]
Also need to remove reference to 'rgb' in docstring for animation plot

**Comment by robbibt** [comment]
One more (super minor) one: in the other dataset notebooks, these headings are nested:

![image](https://github.com/GeoscienceAustralia/dea-notebooks/assets/17680388/704d05b3-5a1c-4d52-b0f6-3acf0d69e5c3)

In the Mangroves ones, they are on the same level:

![image](https://github.com/GeoscienceAustralia/dea-notebooks/assets/17680388/eb958232-7347-4647-a7cb-447197a1274d)

Think they need to be dropped down one heading level.
