### ISSUE TITLE
Helper functions and examples for the SplitMap control in pyleaflet

### ISSUE THREAD

**Issue by uchchwhash** [GeoscienceAustralia/dea-notebooks#1139]
Not sure if this is already implemented and I am just not aware of it.

I am always envious of our ENVI (haha) users who have the ability to lock multiple views/layers together to follow the cursor around. The closest thing that I can think of in the Python world is the SplitMap control that lets you compare two different layers side-by-side.

See https://ipyleaflet.readthedocs.io/en/latest/controls/split_map_control.html

**Comment by robbibt** [comment]
Definitely not implemented by us yet; the `leafmap` package does have an implementation: https://leafmap.org/notebooks/49_split_control/

(It's a pretty cool package actually, would be great to integrate it a bit more in our repo!)

**Comment by uchchwhash** [comment]
The `leafmap` package is not currently available in the sandbox, is it? Looks cool though.

**Comment by robbibt** [comment]
No, it's not - I've only read about it, not used it yet.

**Comment by uchchwhash** [comment]
Just my luck, I may have hit a bug https://github.com/jupyter-widgets/ipyleaflet/issues/453
