### ISSUE TITLE
Is all the Supplementary Data getting used? 

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#1143]
**Describe the bug/issue**
[Supplementary data folder is still using naming conventions from old folder structure](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop/Supplementary_data)
Check if the data is still necessary, and either delete it or update paths

**Comment by robbibt** [comment]
I think it is - those numbered folders refer to the numbered notebooks in the Beginners guide, not the older numbered folders we used to have. 🙂 e.g.: https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop/Beginners_guide
