### ISSUE TITLE
Update our repo readme for DEA knowledge hub

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#1167]
Make updates to the dea-notebooks readme file around interoperability with DEA knowledge hub

- update instructions about the process from going from dev to stable and publishing to dea docs
- update broken links
- check readme makes sense again afterwards

**Comment by BexDunn** [comment]
https://app.sandbox.dea.ga.gov.au/ 

- comment that dea-notebooks publishes to the knowledge hub in the readme
- add the links to the sandbox in multiple places

**Comment by robbibt** [comment]
Is this now complete @benji-glitsos-ga ?

**Comment by benji-glitsos-ga** [comment]
I will need to check all the points are complete and I'll probably need to do some more edits. I'll try to do this today @robbibt

**Comment by benji-glitsos-ga** [comment]
Closing this issue because the PR was merged.
