### ISSUE TITLE
Add new citation to DEA-notebooks  USAGE.rst

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#1178]
https://www.sciencedirect.com/science/article/pii/S156984322400027X 

Add this one to usage file

**Comment by ncimino1** [comment]
Permission to claim this? I'm a first-time contributor.

**Comment by BexDunn** [comment]
Awesome! please do, and thankyou

**Comment by ncimino1** [comment]
Apologies for the delay. I created the pull request with the added citation. Let me know if you have any questions.
