### ISSUE TITLE
Support Dea Waterbodies v3

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-notebooks#1200]
**Describe the bug/issue**
DEA Waterbodies v3 has been released and could be supported using an additional flag in the DEA Tools package.

**Steps to reproduce**
Steps to reproduce the behaviour. For example:
1. Use a v3 geohash sample - r1xghnh04_v3

2. Run get_waterbody() code, an empty dataframe is returned since v2 WFS layer is hardcoded

**Expected behaviour**
Both v2 and v3 geohashes are supported by routing query to appropriate WFS layer.

**Environment information**
What datacube environment are you using? i.e. [CSIRO EASI](https://hub.csiro.easi-eo.solutions/)

**Comment by BexDunn** [comment]
Closed by #1207 and #1199
