### ISSUE TITLE
pyTMD.constants moved to pyTMD.constants.solve

### ISSUE THREAD

**Issue by jessjaco** [GeoscienceAustralia/dea-notebooks#1223]
I'm getting the error `ModuleNotFoundError: No module named 'pyTMD.constants'` when trying to run `dea_tools.coastal.pixel_tides` with dea-tools version 0.3.2 and pyTMD version 2.1.1.

pyTMD.constants, which is imported here: https://github.com/GeoscienceAustralia/dea-notebooks/blob/3d62bb37c77dead10abea20792c8ad51c9fc54dc/Tools/dea_tools/coastal.py#L248 has been moved to `pyTMD.solve.constants`, as described [here](https://github.com/tsutterley/pyTMD/blob/main/pyTMD/solve/constants.py). I'm not sure if this module is even needed in the code, but if it is then the code or version required should probably be updated.

**Comment by jessjaco** [comment]
This issue began with pyTMD version 2.1.1, version 2.1.0 still works.

**Comment by robbibt** [comment]
Hi @jessjaco, yep, pinning it to 2.10 is the solution for now - there were some big breaking changes in the most recent version of pyTMD that we haven't had a chance to look at yet. 🙂

**Comment by robbibt** [comment]
I think this is resolved in the latest version
