### ISSUE TITLE
Update Slack links to Discord

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#1257]
Open Data Cube slack is now deprecated - we should update our slack links to Discord:
https://discord.com/invite/4hhBQVas5U

**Comment by omad** [comment]
Oh cool!

I hadn't seen that! Slack is still listed on the website, datacube core readme, everywhere I can see...

**Comment by benji-glitsos-ga** [comment]
I'll try and do this today

**Comment by robbibt** [comment]
Yep - the process to update those links starts now I think @omad! I might create some issues on those other pages too - please let me know where you spot them!
