### ISSUE TITLE
Token for remote access (vscode)

### ISSUE THREAD

**Issue by ste-goldstein** [GeoscienceAustralia/dea-notebooks#1275]
I used to be able to get a token that allowed connecting to the DEA Jupyter server from VS Code on my local computer.
I cannot find a way to request the token any longer. Is that option still possible.

**Comment by omad** [comment]
When you first sign in to JupyterHub/Sandbox, there's a **Token** link at the top left of the page. Or, you can go to https://app.sandbox.dea.ga.gov.au/hub/token to request a token.

![image](https://github.com/user-attachments/assets/e2ead82c-486f-49f6-b03e-af0c97a64012)
