### ISSUE TITLE
Pylab images not getting rendered in the docs

### ISSUE THREAD

**Issue by andrewdhicks** [GeoscienceAustralia/dea-notebooks#15]
It looks like plots are not appearing when generated with `% pylab notebook`
E.g. http://geoscienceaustralia.github.io/digitalearthau/notebooks/products/GettingStartedWithSentinel2.html#See-what-Sentinel-2-products-are-currently-available

Using `%matplotlib inline` will work, and we could investigate other methods, such as `%matplotlib notebook`

**Comment by robbibt** [comment]
Closing for now; can reopen if we find examples of notebooks that still use `pylab notebook`
