### ISSUE TITLE
Bad link for "Join our Slack community"

### ISSUE THREAD

**Issue by walsh-andrew** [GeoscienceAustralia/dea-notebooks#150]
http://geoscienceaustralia.github.io/digitalearthau/connect/account.html

Hyperlink for "Join our Slack Community" currently points to https://opendatacube.signup.team/

Should point to: https://opendatacube.slack.com ?

**Comment by CEKrause** [comment]
This link is in @andrewdhicks DEA code.

**Comment by BexDunn** [comment]
This has been fixed http://geoscienceaustralia.github.io/digitalearthau/connect/account.html
