### ISSUE TITLE
Bad link on "Loading data" page

### ISSUE THREAD

**Issue by walsh-andrew** [GeoscienceAustralia/dea-notebooks#151]
http://geoscienceaustralia.github.io/digitalearthau/query/Loading%20Data.html

The link right at the bottom of the page takes to a "does not exist page":

http://datacube-core.readthedocs.io/en/stable/dev/generate/datacube.Datacube.load.html

**Comment by CEKrause** [comment]
Also in @andrewdhicks code.

**Comment by robbibt** [comment]
Were these notebooks ('Getting started', 'List products and measurements' , 'Loading data from the datacube') going to be moved over into this repository? @andrewdhicks @CEKrause

**Comment by andrewdhicks** [comment]
That was the plan, but we don't have any more doc taks scheduled for this PI.  I think we probably should try to do something this sprint, as the docs are looking very messy. There are at least 3 pages called "Getting Started"...

**Comment by robbibt** [comment]
Resolved when updating notebooks a few months ago
