### ISSUE TITLE
Intro to Landsat webpage changes

### ISSUE THREAD

**Issue by walsh-andrew** [GeoscienceAustralia/dea-notebooks#154]
http://geoscienceaustralia.github.io/digitalearthau/notebooks/DEA_datasets/Introduction_to_Landsat.html

The abbreviation "SR" is introduced in the NBAR-T section, but it is not defined (presumably 'surface reflectance').  SR can be defined on the first line of the document.

In the first notebook input cell (In [1]:), it says "Import dea-notebook functions. This assumes you are running this notebook from inside the `dea-notebooks` directory. If not, replace the relative `../Scripts` link with a path to the `dea-notebooks/Scripts` directory.

It is not clear how to find the dea-notebooks/Scripts directory. I just tried it with a notebook started using the DEA desktop icon and it still didn't work. So an explanation of starting a notebook from a subdirectory inside a cloned version of dea-notebooks on GitHub is needed.

In the section "Creating a true-colour image using three bands", it is somewhat confusing to talk about making a true colour plot and then having a flag "contrast_enhance=True" that results in a "colour-enhanced image". It's not clear which one is the true colour image (with flag True or False?). Maybe clarifying this will help the user understand what's happening better?

**Comment by robbibt** [comment]
@walsh-andrew Will put these on my to-do list!
