### ISSUE TITLE
Need to fix headings levels in Hovmoller notebooks

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-notebooks#169]
@BexDunn 
Need to reduce the headings levels to at least "##" for all except the first one. (it is not rendering properly on the website with the higher level headings).

**Comment by BexDunn** [comment]
Done by @andrewdhicks  http://geoscienceaustralia.github.io/digitalearthau/notebooks/05_Temporal_analysis/README.html
