### ISSUE TITLE
animated time series function cannot accept dimensions named other than x or y

### ISSUE THREAD

**Issue by seanchua** [GeoscienceAustralia/dea-notebooks#172]
The function :

`DEAPlotting.animated_timeseries` 

requires the dimensions of the input xarray are called x and y when calculating the width ratio:

 `width_ratio = float(ds.sizes['x']) / float(ds.sizes['y'])`

Not essential but would be good to allow for longitude / latitude, lon(g) / lat. More broadly this is an issue I find semi-regularly with functions and libraries related to spatial data so good to keep an eye out for.
@robbibt

**Comment by robbibt** [comment]
Good find, will update this week

**Comment by robbibt** [comment]
@seanchua Can you do `your_xarray_dataset['your_band'].shape` on your dataset and tell me what it gives you? I just want to see what order it returns the dimensions (might be a more reliable way to extract the width ratio)

**Comment by seanchua** [comment]
@robbibt The above returns: 6574 (timesteps), 13 (latitude), 14 (longitude).
