### ISSUE TITLE
Need to update Scripts paths to 10_Scripts in notebooks

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#186]
Scripts folders have been moved - we need to update our paths for loading dea_notebooks from Scripts to 10_Scripts.

**Comment by BexDunn** [comment]
we're working on this!

**Comment by BexDunn** [comment]
I'm on intro to fractional cover in the DEA Datasets folder

**Comment by BexDunn** [comment]
Also adding the helpful header text:

You need to run the following commands from the command line prior to launching jupyter notebooks from the same terminal so that the required libraries and paths are set:

`module use /g/data/v10/public/modules/modulefiles` 

`module load dea`

If you find an error or bug in this notebook, please either create an 'Issue' in the Github repository, or fix it yourself and create a 'Pull' request to contribute the updated notebook back into the repository (See the repository README for instructions on creating a Pull request).

The examples provided here can be found as notebooks in the [dea-notebooks Github repository](https://github.com/GeoscienceAustralia/dea-notebooks). Note that these functions have been developed by DEA users, not the DEA development team, and so are provided without warranty. If you find an error or bug in the functions, please either create an `Issue` in the Github repository, or fix it yourself and create a `Pull` request to contribute the updated function back into the repository (See the repository README for instructions on creating a Pull request).

**Comment by CEKrause** [comment]
Hi @Bartesto. Can you please let us know exactly what you tried to run and what failed so we can track the problem and fix it. Thanks.

**Comment by Bartesto** [comment]
Hi Robbi,

Thanks for getting back to me. I’m out of office for 2 weeks so will get back in touch down the track. 

Cheers
Bart

**Comment by BexDunn** [comment]
I think we've got all of these. I'm going to close the issue. Please reopen if you find more problems. specifically with the /10_Scripts path not being updated from /Scripts, or open a new issue for other problems.
