### ISSUE TITLE
Files and images are being moved to Supplementary data folder

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#198]
Moving files from 02_DEA_datasets/Files to Supplementary_Data/Images

Moving files from 09_Workflows/  mv *.png ../Supplementary_Data/Images/

**Comment by robbibt** [comment]
Robbi will update `RandomForest` and `GettingStartedwithLandsat`/`PQ` notebooks

**Comment by BexDunn** [comment]
I'm going to close this as this is now an established feature :)

**Comment by BexDunn** [comment]
I noticed there are still images in 09_Workflows that we should move over.
