### ISSUE TITLE
Join our Slack community link is hard to find

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#217]
http://geoscienceaustralia.github.io/digitalearthau/connect/account.html  

"Getting Help" is in a drop-down under 'NCI Account Registration"

-can we please move it up to the same level? it's hidden as a default.

it makes it hard to find the Slack sign-up link.
http://geoscienceaustralia.github.io/digitalearthau/connect/account.html#getting-help

**Comment by CEKrause** [comment]
Pull request in with the main repo to fix this.

**Comment by robbibt** [comment]
Hey @CEKrause , did this get fixed?

**Comment by CEKrause** [comment]
Yes! It just got pulled into the main dea repo. It's still a little skewy with the formatting, but it's now easier to find.
