### ISSUE TITLE
Pixel Drill With Widgets path incorrect

### ISSUE THREAD

**Issue by qbastian** [GeoscienceAustralia/dea-notebooks#245]
In the first cell the path is:

sys.path.append(os.path.expanduser('~/dea-notebooks/10_Scripts'))

which doesn't work.

I have used:

sys.path.append('../10_Scripts/')

which does work.

**Comment by BexDunn** [comment]
this does assume that you put it in your home directory. Which I didn't either. I'll add in the option?
