### ISSUE TITLE
Bug in `load_clear` functions in DEADatahandling

### ISSUE THREAD

**Issue by s-m-t-c** [GeoscienceAustralia/dea-notebooks#255]
If you set the output CRS to WGS84 when passing a query to the `load_clear` functions within `DEADatahandling` an error occurs in the calculation of `data_perc` as the `x` and `y` dimensions are returned as `longitude` and `latitude` and this breaks the line:
`data_perc = good_quality.sum(dim=['x', 'y']) / (good_quality.shape[1] * good_quality.shape[2])` 

A change to make this dimension title agnostic should solve the problem. 
eg. `data_perc = good_quality.sum(axis=1).sum(axis=1) / (good_quality.shape[1] * good_quality.shape[2])`

Something to implement after we return from break.

**Comment by robbibt** [comment]
Closed by #260
