### ISSUE TITLE
capitalization and index.rst

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#307]
@cbur24 - can you please update the notebook file name parallel_segmentation.ipynb to match the sentence case convention  Parallel_Image_Segmentation.ipynb ? and also add it to the index.rst file in 09_Workflows? It's a lovely notebook!

**Comment by cbur24** [comment]
Two pull requests made:
- notebook now matches the naming convention 
- readme has been updated.
