### ISSUE TITLE
Issue with bands_of_interest in load_nbarx

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#32]
@CEKrause @BexDunn I've had some issues with the `bands_of_interest` parameter in load_nbarx: any time I try to specify a set of bands, the function crashes out with a key error `KeyError: 'bands_of_interest'`. It works fine when no bands are specified.

I think this is because the function wants `bands_of_interest` given to it as a **kwarg, which only works when expanding dictionaries. I was thinking I might edit the function to define `bands_of_interest` as a simple variable like this:

`load_nbarx(dc, sensor, query, bands_of_interest, product = 'nbart', filter_cloud = True)`

...but this will definitely break people's code if the current function works for them. Would anyone strongly object if I made this change? (just opening this up for discussion because it's probably the single most-used function in the repository at this stage)

**Comment by robbibt** [comment]
Actually, by defining a default value to bands_of_interest like `bands_of_interest = ""` , the existing `if bands_of_interest:` bit should make it work without breaking code... might give this a go next week!

**Comment by BexDunn** [comment]
default value might need to be red, green, blue, swir, nir? I guess we want default to be all bands?
 @CEKrause @robbibt

**Comment by robbibt** [comment]
Closed by #34
