### ISSUE TITLE
Supporting both lab and notebook

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/dea-notebooks#343]
Most notebooks use `%matplotlib inline`, but some use `%pylab notebook`. Latter only works inside `notebook` but not in `lab`, in `lab` one needs to use `%pylab widget` to get similar effect.

Not sure if notebooks with `%pylab notebook` **need** to have interactive graphs or this just a nice to have.

Also note that `%pylab` magic is kinda deprecated in favor of `%matplotlib` (`%pylab` imports some functions from `numpy/scipy` into global namespace to be more Matlab-like)

- 03_Integrating_external_data/CreateRasterMaskFromShapefile.ipynb
- 04_Index_calculation/Mineral_Indices_Calculation.ipynb
- 05_Temporal_analysis/InterrogateCropPolygonForPhenology.ipynb
- 05_Temporal_analysis/Interactive_phenology_plot_tagged.ipynb
- 05_Temporal_analysis/PixelDrillWithWidgets.ipynb
- 06_Composite_generation/Create_a_spectral_plot_for_Sentinel2.ipynb
- 09_Workflows/Generate_Mangrove_Cover_Statistics_Through_Time.ipynb
- 09_Workflows/RetrieveLandsat8ViewAndExport.ipynb

**Comment by robbibt** [comment]
All notebooks in `develop` have been updated for use in Jupyter Lab (e.g. removed `%pylab notebook` in favour of `%matplotlib inline`)
