### ISSUE TITLE
Incompatibilities between NCI and DEA Sandbox environments

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#344]
Issue to record any inconsistencies we find between the NCI and DEA Sandbox environments, including:
- Any modules/python packages not installed on both environments
- Any missing Jupyter lab extensions
- Any key datasets not indexed on both environments
- etc

**Comment by cbur24** [comment]
- The python module `scikit-learn` is not installed on the DEA Sandbox 

- `datacube_stats` is not installed on the DEA Sandbox (work is currently being done to make it compatible, a local install will work for some stats)

**Comment by robbibt** [comment]
- [x] I've now thoroughly tested the `OTPS` tidal model on the Sandbox, and it looks like everything is working well

**Comment by robbibt** [comment]
- [ ] Sentinel 2 Near-Real-Time data isn't currently available on the NCI

**Comment by BexDunn** [comment]
module `digitalearthau` is not available on the DEA Sandbox. This module has the wofs fusing function in it

**Comment by robbibt** [comment]
- [ ] `wofs_albers` currently needs the user to specify `output_crs` and `resolution`, which isn't necessary on the NCI (see https://github.com/GeoscienceAustralia/dea-config/issues/405)

**Comment by robbibt** [comment]
[ ] There is no DEM available on the sandbox (on the NCI, we have the 30 m SRTM DEM e.g. `dc.load(product='srtm_dem1sv1_0', **query)`)

**Comment by uchchwhash** [comment]
If there's no security concerns that prevent us from doing so, having `ssh` would be nice on the sandbox.

**Comment by Kirill888** [comment]
@uchchwhash one can always download whatever binary and run it, so...

**Comment by CEKrause** [comment]
The sandbox is missing `descartes`, which is required to plot shapefiles using geopandas.

**Comment by cbur24** [comment]
The remote sensing package `rsgislib` cannot be installed on the Sandbox as it requires a conda installation. https://www.rsgislib.org/download.html

**Comment by cbur24** [comment]
The version of GDAL on the Sandbox does not appear to have the .kea driver. https://gdal.org/drivers/raster/kea.html

**Comment by robbibt** [comment]
- [ ] The `seaborn` module for producing scientific plots is currently missing from the Sandbox (e.g. `import seaborn as sns`)

**Comment by robbibt** [comment]
- [ ] `ffmpeg` is missing from the Sandbox. This is needed for generating animations based on satellite data

Issue: https://github.com/GeoscienceAustralia/dea-sandbox/issues/23

**Comment by robbibt** [comment]
- [ ] Virtual products functionality requires a version of `datacube-core` > 1.7. This is currently not the case on the sandbox

**Comment by uchchwhash** [comment]
Happy to report that the incompatibilities are now less in number:

1. `datacube-core` has been updated to virtual products' liking
2. `ffmpeg` seems to work
3. `seaborn`, `scikit-learn`, `datacube-stats` should be there
4. I may have been `descartes`, apologies
5. the `.kea` and `rsgislib` story is more complicated, sorry @cbur24 !

**Comment by uchchwhash** [comment]
Update!

1. `descartes` should now also be available

Please restart your servers in the sandbox if you need this.

**Comment by robbibt** [comment]
* `%load_ext line_profiler` is not installed on the DEA Sandbox. This is really useful for trouble-shooting code, and it would be great to have it available.

**Comment by robbibt** [comment]
* [ ] Radar products such as `s1_gamma0_geotif_scene` are not currently available on the NCI datacube

**Comment by robbibt** [comment]
This has served its purpose, closing for now
