### ISSUE TITLE
Tags in Tags Index link to glossary rather than notebooks

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#37]
Tags that are also mentioned in the DEA Glossary link to the glossary page, not notebooks.

To reproduce:
1) Visit [Tags index](http://geoscienceaustralia.github.io/digitalearthau/genindex.html)
2) Click a tag like "DEA" which is also included in the Glossary

You are directed to the [Glossary](http://geoscienceaustralia.github.io/digitalearthau/about/glossary.html#term-dea) page rather than the corresponding Jupyter notebook

**Comment by robbibt** [comment]
Actually, a related issue: what _is_ the intended behavior when you click on a tag? Currently it links to the first (?) notebook with the tag, but ideally you would want to get back a list of matching notebooks.

**Comment by andrewdhicks** [comment]
We are reusing the glossary index as our tags index, so they are mixed in, with the glossary terms in bold. Is there a notebook with a tag like "DEA" that isn't getting linked?

With multiple notebooks with the same tag, that's when you get the `[1]` after the term.

**Comment by robbibt** [comment]
Ah, no worries; I assumed the tag list just contained tags imported from the notebooks (the tags don't show up on notebooks rendered in Github so it's difficult to check what notebooks have what tags). From the sound of this it's all working as it's meant to.

**Comment by andrewdhicks** [comment]
It is still all an experiment, so it is more of a matter of is it useful/understandable, rather than any sort of design.
