### ISSUE TITLE
load_clearlandsat() function under 10_Scripts is broken

### ISSUE THREAD

**Issue by prl900** [GeoscienceAustralia/dea-notebooks#377]
This [line](https://github.com/GeoscienceAustralia/dea-notebooks/blob/657de085b2dc638d724ab04fc1349753452a731e/10_Scripts/DEADataHandling.py#L496) uses an undefined variable.

Seems to be fixable just by replacing the `combined_ds` variable name with `sensor_ds`.

Happy to submit a PR if that's accepted.

**Comment by BexDunn** [comment]
totally accepted! if you pop a PR in, I'll take a look :)

**Comment by BexDunn** [comment]
@prl900 I've sent you a link to give you repo access

**Comment by BexDunn** [comment]
fixed
