### ISSUE TITLE
Scripts vs algorithms:

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#38]
Hey friends,
Thoughts on creating a subfolder/an alternate folder for scripts vs algorithms? Because we have plenty of scripts to load, and they aren't necessarily notebook examples of using algorithms?
Bex

**Comment by robbibt** [comment]
I agree; the algorithms directory feels a little awkward now that it is filled up with python scripts. Could the two notebooks in there be moved elsewhere to make it just python files? My one (random forest) could probably work in either case_studies and workflows.

On that topic, I'm also not entirely convinced that we need separate case_studies and workflows directories... both seem very similar in scope.

**Comment by robbibt** [comment]
Actually `scripts` probably is a better description for a directory of only python scripts

**Comment by rjdunn** [comment]
yes - shall we create a scripts directory?

**Comment by robbibt** [comment]
This has been superseded by the big shuffle that just happened - closing for now
