### ISSUE TITLE
Add ML notebook to demo dea_classificationtools

### ISSUE THREAD

**Issue by richardt94** [GeoscienceAustralia/dea-notebooks#380]
Seems like it would be a good idea to write a notebook as part of the refresh to demonstrate the functions in the dea_classificationtools module, otherwise users may not be aware that the ML functionality exists.

**Comment by robbibt** [comment]
Yep, definitely agree: it'd be great if we had an demo notebook for each function we add to `Scripts` so people have a starting point to using the functions.

Feel free to make a `Frequently_used_code` notebook for each different ML functionality you add - I think several smaller/discrete notebooks will be easier to use than fewer long/complex notebooks.

**Comment by s-m-t-c** [comment]
Pull request here: https://github.com/GeoscienceAustralia/dea-notebooks/pull/462

**Comment by robbibt** [comment]
@s-m-t-c  Can this be closed now?
