### ISSUE TITLE
Allow map_shapefile to plot colours based on attribute

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#477]
Currently, the `map_shapefile` function (https://github.com/GeoscienceAustralia/dea-notebooks/blob/master/Scripts/dea_plotting.py#L330) plots each feature in a shapefile with an incrementing colour. 

It would be far more useful if this function plotted features based on values from a field in the shapefile attribute table.

**Comment by s-m-t-c** [comment]
The next steps are to develop some logic regarding the treatment of categorical and continuous variables and use some of the ideas from this leaflet [example](https://leafletjs.com/examples/choropleth/). This will be inserted near line 392 as an option enabled when a string containing the attribute column name we wish to colour the features by is passed into the function.

Need to spend some more time thinking about how to bin and organise the colours for continuous values. This will probably live in a `get_colour` function similar to that shown in the linked example.

**Comment by robbibt** [comment]
@s-m-t-c The above sounds great to me. For the simplest continuous numbers case, I imagine we want to generate a unique, linearly spaced colour stretched between the lowest and the highest values? So, kind of linearly sampling a colour map based on the values in the attribute table? More complex binning (e.g. assigning a specific colour to appear at a specific value) is probably possible but a fair bit more complicated

**Comment by robbibt** [comment]
@s-m-t-c Categorical mightn't be that hard to implement: if there's e.g. 4 classes/unique values in the attribute column, simply sample the cmap four times, evenly spaced?

**Comment by s-m-t-c** [comment]
@gabzgit for your reference
