### ISSUE TITLE
Add nbar(t) contiguity masking to load_ard

### ISSUE THREAD

**Issue by cbur24** [GeoscienceAustralia/dea-notebooks#485]
When loading GA Landsat Collection 3 data, the current iteration of `dea_datahandling.load_ard ` masks invalid pixels using only `fmask`.  Including masking by the `oa_nbar(t)_contiguity` band would further reduce the number of noisy pixels included in the returned dataset.  Agnostic about whether this should be by default or added as an optional flag.

**Comment by robbibt** [comment]
Fixed by #487
