### ISSUE TITLE
FutureWarning: '+init=<authority>:<code>' syntax is deprecated

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#486]
Notebooks using the `display_map` and `map_shapefile` functions (that I'm aware of at the moment, there could be more) are currently producting the following warnings:

![image](https://user-images.githubusercontent.com/17680388/73045286-5e4df900-3ec1-11ea-9034-dff6e9b411d2.png)

While this doesn't break anything, we should revise those functions to try and address this warning.

**Comment by erialC-P** [comment]
This issue pops up in the DEA_datasets notebook on TSmask
