### ISSUE TITLE
TSmask flags have changed to be consistent with fmask breaks DEA_datasets/TSmask

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/dea-notebooks#512]
`s2_tsmask` product now has flags with the same names as `fmask`

`No observation` -> `nodata`
`Clear` -> `valid`
`Cloud` -> `cloud`
`Cloud shadow` -> `shadow`

**Comment by robbibt** [comment]
That's actually a really nice change, should make things easier in the future

**Comment by cbur24** [comment]
With this change, will the following still produce a cloud free mask?

`from datacube.storage.masking import make_mask`
`cloud_free_mask = make_mask(tsmask_ds.classification, classification='valid')`

**Comment by robbibt** [comment]
Fixed by #553
