### ISSUE TITLE
Create `xr_geomedian` notebook for `frequently_used_code` folder

### ISSUE THREAD

**Issue by cbur24** [GeoscienceAustralia/dea-notebooks#513]
@Kirill888 's `xr_geomedian` [notebook](https://github.com/opendatacube/odc-tools/blob/master/notebooks/geomedian-example.ipynb) would make a nice addition to the `frequently_used_code` folder of dea-notebooks.  The current [Geomedian_composites](https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Frequently_used_code/Geomedian_composites.ipynb) notebook is very computationally expensive, and thus limits the analysis extent that users can apply it too.

**Comment by robbibt** [comment]
Closed by #521
