### ISSUE TITLE
Allow user to also export geotiff of heatmap from Change Filmstrips notebook

### ISSUE THREAD

**Issue by GeoRach** [GeoscienceAustralia/dea-notebooks#531]
Can currently export the time composites as geotiffs, but not the resulting heatmap. The heatmap is really useful to import into other project GIS (e.g. DEA CoastLines) to understand / compare those outputs and refine method.

**Comment by jennet333** [comment]
https://github.com/GeoscienceAustralia/dea-notebooks/issues/531#issue-571721388

**Comment by robbibt** [comment]
Looks like this is now included in the latest version of the notebook
