### ISSUE TITLE
Update repository with recent DigitalEarthAfrica notebooks and code

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#533]
In the recent ODC Hackathon 2020 there were some major additions and updates to code in the DEAfrica notebooks repository (https://github.com/digitalearthafrica/deafrica-sandbox-notebooks).

We should keep a list of relevant things that were updated in DEAfrica notebooks/code so that we can port them back over to `dea-notebooks`.

@cbur24, @caitlinadams, if you get a chance can you comment with any new notebooks/functionality that was developed during the hack that you think would also be useful to include in `dea-notebooks`? I'm thinking things like the `Dask` notebook I saw that would work just as well in the Australian context.

**Comment by caitlinadams** [comment]
- We're most of the way through an introductory notebook to explain Dask: https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/pull/38
- Potentially the Sentinel-1 notebook: https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Datasets/Sentinel_1.ipynb
- Possibly the Urbanization case study I started: https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/pull/37 -- However, I think this should probably be reworked to focus less on calculating a sustainable development goal, and potentially more on an Australian industry/monitoring kind of question

**Comment by cbur24** [comment]
- The format/structure of the[ Landsat Collections](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/refactor_loadard/Datasets/Landsat_collections.ipynb) notebook could work well for Aus.  Would need to switch out the USGS Landsat collections C1 & C2 for the Aus variants C3 & C2.
- [Wetlands Insight Tool](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Real_world_examples/Wetlands_insight_tool.ipynb) notebook under `Real_world_examples`.  Some adjustments would need to be made to the [deafrica_wetlandstools.py](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Scripts/deafrica_wetlandtools.py) script to make it work for Aus.

**Comment by robbibt** [comment]
Another one I noticed come up in Github emails: was there a bug fix to `mostcommon_crs` to allow it to work when certain query/data load params are passed to it? @cbur24

**Comment by cbur24** [comment]
Yes, that's right @robbibt . Pretty basic, I just removed the offending params:
```
query = deepcopy(query)
    if 'dask_chunks' in query:
        query.pop('dask_chunks', None)

    if 'align' in query:
        query.pop('align', None)
```

A better fix might be to take the query input and only select the params that `mostcommon_crs` requires (time, lat, lon)

**Comment by cbur24** [comment]
A [soil moisture notebook](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Datasets/Soil_Moisture.ipynb) has recently been added to the 'Datasets' folder in the DE Africa repo. Uses a global dataset at 10km resolution so should be useful for Australia too

**Comment by caitlinadams** [comment]
I've added a notebook on [generating median, mean, min and max composites](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Frequently_used_code/Generating_composites.ipynb) to go along with the geomedian notebook. This largely replaces the functionality offered by the DCAL mosaic notebook.

See the [PR](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/pull/83) for details, as I also changed the title of the existing geomedians notebook to group them together.

**Comment by cbur24** [comment]
- A notebook on downloading and anlaysing [ERA5 reanalysis climate data](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Datasets/Climate_Data_ERA5_AWS.ipynb)
- Major update to the training data function(s) in `dea_classificationtools.py`, runs in parallel now and can accept a custom function. Line 305 to 650 [here](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/7666ad943fdc2968da63524da321442ed250d46e/Scripts/deafrica_classificationtools.py#L305)

**Comment by andrewdhicks** [comment]
Added `ds.sel(method='...')` examples in `Frequently_used_code/Working with time in xarray` notebook in this [PR](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/pull/109).

**Comment by cbur24** [comment]
New `Frequently_used_code` notebook demonstrating a[ PCA on multispectral data ](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Frequently_used_code/Principal_component_analysis.ipynb)

**Comment by cbur24** [comment]
Two new `Beginners_guide` notebooks:
- [Intro_to_numpy](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Beginners_guide/06_Intro_to_numpy.ipynb)
- [Intro_to_xarray](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Beginners_guide/07_Intro_to_xarray.ipynb)

**Comment by cbur24** [comment]
New notebook [Vegetation_phenology](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Frequently_used_code/Vegetation_phenology.ipynb), and accompanying script [deafrica_temporal_statistics](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Scripts/deafrica_temporal_statistics.py)

**Comment by robbibt** [comment]
This is done, but we should revisit in the future
