### ISSUE TITLE
Operational NDVI seasonal anomalies 

### ISSUE THREAD

**Issue by cbur24** [GeoscienceAustralia/dea-notebooks#546]
NSW DPI wishes to use the DEA satellite archive to operationally produce seasonal NDVI anomalies for their [State Seasonal Update](https://www.dpi.nsw.gov.au/climate-and-emergencies/seasonal-conditions/ssu/march-2020).  The code for doing this currently exists [here](https://github.com/GeoscienceAustralia/dea-notebooks/tree/chad/vegetation_anomalies), but requires a number of improvements to make it ideal for its purpose.  The following needs to be explored/implemented:
- Sensor fusion between LS8 and S2 for producing the NDVI seasonal composite - if this works, then data gaps, especially during winter months, will be mitigated. The code for doing this could also form the basis for a more general function to sit in `Scripts/dea_datahandling` allowing sensor fusion when dealing with band indices.
- Using one of the summary WOfS products, water-bodies should be masked in the final NDVI anomaly product.
- Seasonal composites are currently built from C2. The code base needs to be able to switch to using C3 when C3 becomes operational. So the code should have a parameter to specify which collection to use (as it currently does).
- The processing pipeline should be as automated as is practical.  Ideally a single python or shell script that runs all the steps. Currently a short jupyter notebook runs all the steps in the VDI. However, including S2 and WOfs images will likely overwhelm the memory on the VDI so it may have to be re-written to work on Gadi.
- Ideally, the code should be commented enough to allow storing it under the `Scientific_workflows` folder on `dea-notebooks` repo
- On the admin side of things, a formal agreement between NSW DPI and GA may need to take place regarding the time-line of production - potentially this could allow NSW to delay releasing the seasonal update until all satellite images for the season are available.

The points above form the core functionality required. But further minor requirements may be added here in the near future (e.g. the ability to export just the NDVI composite rather than the anomaly).

**Comment by CEKrause** [comment]
Re point two. Mask out any negative values as we go through the process so that they don't bias the final average number.

**Comment by cbur24** [comment]
I've changed the filepaths for fetching the mosaics to absolute paths in the `anomalies.py` script.

All the NDVI climatology mosaics are located here:
- std dev : `/g/data1a/r78/cb3058/dea-notebooks/vegetation_anomalies/results/NSW_NDVI_Climatologies_std/mosaics`
- means : `/g/data1a/r78/cb3058/dea-notebooks/vegetation_anomalies/results/NSW_NDVI_Climatologies_mean/mosaics`

The project folder with all scripts and results is here: `/g/data1a/r78/cb3058/dea-notebooks/vegetation_anomalies`

**Comment by jwurtzel** [comment]
Need to change file output names to have 'ndvi' at the front, followed by date.  Some programs apparently do not like files to start with numeric characters.

**Comment by cbur24** [comment]
Something else to keep in mind: when I computed the NDVI climatologies I forgot to set `align=(15,15)` in the config yaml.  As such, the pixels in the climatologies are edge aligned rather than centre aligned. So, if/when loading Landsat C3 to calculate seasonal composites, do not set the `align` parameter in the `dc.load()`.  C2 is edge aligned so the climatolgies will align with C2.

**Comment by robbibt** [comment]
Closing as we don't currently have plans for this - can re-open if we do!
