### ISSUE TITLE
Dask dashboard link not correct on sandbox

### ISSUE THREAD

**Issue by andrewdhicks** [GeoscienceAustralia/dea-notebooks#554]
The code to set up the proxy link to the dask daskboard when running on the sandbox isn't getting called.
https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Scripts/dea_dask.py#L59

It looks like the environment variable `AWS_ACCESS_KEY_ID` is no longer being set on the sandbox.

Issue originally identified by @eloise-b

**Comment by andrewdhicks** [comment]
Ping @cbur24

**Comment by cbur24** [comment]
Has anyone else had the issue @eloise-b mentioned? I can generate a local dask cluster on the sandbox without complaint. 
I'm still getting the `bokeh.protocol.exceptions.ProtocolError: Subprotocol header is not 'bokeh'` when I try to use the printed hyperlink, but that's a known bug that's being worked on.

Sometimes if you generate a local cluster on more than one notebook then the 8787 port is filled and a random one is created instead. In which case you need to manually add the hyperlink to the dask-dashboard to get the progress plots to work, was that the issue Eloise had?

@Kirill888

**Comment by eloise-b** [comment]
I'd only generated the cluster in one notebook, but manually adding the url and making it of the format suggested in the notebook worked. The url it gave me was the same format as a server (numbers and fullstops), rather than a url (if that makes sense?).
![Screen Shot 2020-04-21 at 2 48 53 pm](https://user-images.githubusercontent.com/13390614/79952233-741d8b00-84bd-11ea-9d27-bef64623916e.png)

**Comment by Kirill888** [comment]
@cbur24 I'm testing on `master` branch and it works for me in the sandbox, I do have some feedback about `create_local_dask_cluster` function though:

1. This code has no effect when moved into function, you should just delete it
https://github.com/GeoscienceAustralia/dea-notebooks/blob/f4f7d00452953e29ee35ec4efc46b2541d8334db/Scripts/dea_dask.py#L61-L65
2. Code that configures dask url only runs when `AWS_ACCESS_KEY_ID` is set, as Andrew pointed out previously. Maybe it's best to move it out of that `if` statement and run it always
https://github.com/GeoscienceAustralia/dea-notebooks/blob/f4f7d00452953e29ee35ec4efc46b2541d8334db/Scripts/dea_dask.py#L67-L69

I'm not sure why `AWS_ACCESS_KEY_ID` is not set for @eloise-b, I assumed it was set for everyone, but maybe not?

**Comment by cbur24** [comment]
@Kirill888 
1. That chunks of code is removed in PR #513, see the last comment in the thread
2.  So if we move it out of the if-statement it won't cause the code to fail if run on the NCI?

I'm pretty swamped for work right now so would appreciate it if someone else could make this PR if need be.  As I see it, the code, while not perfect, shouldn't be creating any issues - except in @eloise-b's case

**Comment by Kirill888** [comment]
Agree code should work on sandbox, according to Tom every user should have `AWS_ACCESS_KEY_ID` in AU sandbox. 
I'll do a PR for `dea_dask` changes.

**Comment by andrewdhicks** [comment]
I don't have AWS_ACCESS_KEY_ID set either, cc @tom-butler
