### ISSUE TITLE
`skimage.measure.find_contours` expects numpy array not xr.DataArray

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/dea-notebooks#579]
This came up when testing new sandbox image, updating `skimage` caused error here:

https://github.com/GeoscienceAustralia/dea-notebooks/blob/1112e810c4f6e9908e03d7afdfaae8696ad4aef4/Scripts/dea_spatialtools.py#L406

Should be

```python
 for i in find_contours(da_i.data, z_value)
```

**Comment by robbibt** [comment]
Thanks Kirill, this will probably affect some of the Real world example notebooks too. I'll have a look and fix it up
