### ISSUE TITLE
Machine learning notebook fails on NCI

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#581]
The `Machine learning with the Open Data Cube` notebook currently fails on the NCI (on both `module load dea` and `module load dea/20200526` with the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9f059c61b145> in <module>
      6 import datacube
      7 import matplotlib
----> 8 import pydotplus
      9 import numpy as np
     10 import geopandas as gpd

ModuleNotFoundError: No module named 'pydotplus'

dea-notebooks/Frequently_used_code/Machine_learning_with_ODC.ipynb
```

It looks like `pydotplus` does not exist on the NCI environment. We should either get this package installed into the latest `module load dea`, or update the notebook so it does not need this package. 

I believe recent versions of `sklearn` include a built-in `plot_tree` function that doesn't require  `Graphviz`, so it might be a good opportunity to swap over: 

https://twitter.com/justmarkham/status/1250767400259268608

**Comment by Kirill888** [comment]
`pydotplus` is a simple dependency, I don't remember deleting it. It was probably pulled in by something we had to disable previously or something that no longer uses it. We can probably add it in explicitly into dea env. But regardless, fewer dependencies is better.

**Comment by s-m-t-c** [comment]
In my opinion the `graphviz` approach that `pydotplus` enables creates easier to interpret trees (colours etc) than the built-in plotting function. Would prefer to leave as is because the package is being added in https://github.com/GeoscienceAustralia/dea-orchestration/pull/174 . If there's a strong opinion otherwise I can modify the notebooks otherwise we can close this issue.

**Comment by robbibt** [comment]
Nice, that sounds fine to me 👍

**Comment by robbibt** [comment]
This no longer fails on the NCI
