### ISSUE TITLE
Need to regenerate netcdfs in Supplementary Data

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/dea-notebooks#582]
There has been a slight change in the way netcdfs from datacube are generated. Basically `crs` data variable is now called `spatial_ref` and is marked as a coordinate. This allows output  of `xr.open_dataset` to be compatible with `.geobox` property from `datacube`.

Currently this notebook is failing to display loaded netcdf file

`https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Frequently_used_code/Opening_GeoTIFFs_NetCDFs.ipynb`

Failure is here:

https://github.com/GeoscienceAustralia/dea-notebooks/blob/1112e810c4f6e9908e03d7afdfaae8696ad4aef4/Scripts/dea_plotting.py#L150

Because `.geobox` property is `None`. This also means that `rgb` method can only display geo-registered imagery. I recommend using this method instead `datacube.utils.spatial_dims`

https://github.com/opendatacube/datacube-core/blob/c2c25d3df437218223b900c1e6deb6f3dce374e4/datacube/utils/math.py#L38-L51

**Comment by robbibt** [comment]
@Kirill888 The intention of that notebook is to demonstrate how any NetCDF file could be loaded and analysed alongside DEA data, so I guess we don't necessarily want to regenerate "nice" compliant NetCDFs (as these won't be what other users want to use). 

I think updating `rgb` to plot datasets that don't have a geobox might be better, and it looks like `datacube.utils.spatial_dims` is a easy replacement.

**Comment by Kirill888** [comment]
Agree that `rgb` needs fixing, and while the fix is "easy", this function is a recent addition and might not work in some outdated environments.

**Comment by robbibt** [comment]
Yeah OK... do you know by any chance whether it is included in `module load dea/20200526` on the NCI?

**Comment by Kirill888** [comment]
yes, it would be included in 1.8.0+ for sure
