### ISSUE TITLE
update exporting geotiff notebook to use write_cog

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#586]
write_geotiff has been deprecated by write_cog in datacube 1.8.0 https://datacube-core.readthedocs.io/en/latest/about/whats_new.html 

- update the exporting geotiff notebook
- maybe also update the script if it needs it?

**Comment by caitlinadams** [comment]
Chad's initial notes on what needs to be done:

1. Use the info here: https://datacube-core.readthedocs.io/en/latest/dev/api/generate/datacube.utils.cog.write_cog.html to re-write the Exporting_GeoTIFFS.ipynb file: `from datacube.helpers import write_geotiff` function is being replaced by the datacube.utils.cog.write_cog function.  Be sure to make a note of the extra memory limitations of this function, and leave the code block on using the array_to_geotiff function so a user can decide not to use the write_cog function if they prefer not to use the extra memory.
2. Go through the Frequently_used_code and Real_world_examples folders and replace any write_geotiff code blocks with write_cog . 

Any other recommendations for what specifically needs to be done appreciated!

**Comment by BexDunn** [comment]
Additonally please explicitly pass dtype and nodata from the rasterio options in

**Comment by robbibt** [comment]
I might have a go at this this week if that's OK?
