### ISSUE TITLE
Rename 'master' branch to something else

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-notebooks#589]
Suggestions have been 'main' or 'stable'

**Comment by CEKrause** [comment]
We will however need to get Core team to update both:
- The User Guide (currently built off "master")
- The automated Sandbox syncing (currently synced from "master")
Some other thins that will need to be updated:
- The DEA notebooks readme page
- The DEA notebooks wiki page

**Comment by CEKrause** [comment]
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by robbibt** [comment]
I vote for `stable`! I think it's a more descriptive counterpart to `develop`.

**Comment by BexDunn** [comment]
I like stable as well! And I think we should add a comment in the top of the readme that stable is the stable branch, + do a find+ replace in our readme and wiki

**Comment by BexDunn** [comment]
Steps:
- [X] create  `stable` branch
- [X] set docs to build off `stable`
- [x] update readme and wiki
- [x] set sandbox to sync from `stable`
- [ ] archive master
- [ ] delete master

**Comment by BexDunn** [comment]
[x] create `stable` branch

**Comment by robbibt** [comment]
We should also copy the latest version of the new `stable` branch code onto the NCI folder that is used to give users access to `dea-notebooks` when they install `digitalearthau` for the first time. It hasn't been updated since the notebooks refresh almost a year ago.

**Comment by robbibt** [comment]
#683 updates the readme to change `master` refs to `stable`

**Comment by robbibt** [comment]
@BexDunn Both the user guide and Sandbox have now been updated to use `stable`, I guess that just leaves archiving/deleting `master` now?

**Comment by BexDunn** [comment]
> @BexDunn Both the user guide and Sandbox have now been updated to use `stable`, I guess that just leaves archiving/deleting `master` now?

Yep, should we archive, with a plan to delete in a month, or should we just go ahead and delete? I vote archive, because that way we won't randomly break stuff for people who haven't looked at the repo this week. Should we announce to dea-notebooks and/or user emails that we've updated the stable branch? maybe we could get the Sandbox crew to let people know?

**Comment by robbibt** [comment]
This is done!
