### ISSUE TITLE
Add 'align' to the loading data notebook in the beginners' guide

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#601]
Explain align, (below is thanks to @Kirill888) in the loading data notebook to help with Collection 3 upgrade.

do I need align?
I want native projection pixels without 1/2 pixel offset
I'm supplying UTM zone  CRS copied from datasets objects
I'm supplying native resolution
I'm using landsat product from the new collection that places pixel centers rather than pixel edges at 0
ALL of the above must hold before you need align

**Comment by robbibt** [comment]
This was recently addressed in the "DEA Landsat surface reflectance" notebook:
https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/DEA_datasets/DEA_Landsat_Surface_Reflectance.ipynb

As it's specific to Collection 3 Landsat, I think we can close this for now without also adding it to the Beginner's guide.
