### ISSUE TITLE
Explain dc.load calls thoroughly in the doco

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#602]
Currently load_ard wraps dc.load. load_ard has a link to the dc.load doco here: 
https://datacube-core.readthedocs.io/en/latest/dev/api/generate/datacube.Datacube.load.html 
however, that documentation is good at telling you what the call is but not why you may or may not need it. I'm suggesting we add a ' How to load data from the datacube' section into the Wiki, somewhere nice and obvious, and explain 'align' and 'resolution' and the fuse functions, really thoroughly with examples, so that we get super comfortable using all the extra useful bits. 

For discussion: we can update the loading data notebook in the beginners guide, or the wiki, or both. I'm voting for both here but willing to be told that is too much?

Alternatively we could contribute the information to the docs for Core, and link nice and prominently to that?

**Comment by robbibt** [comment]
I think both is sensible, perhaps with priority given to [04_Loading_data.ipynb](https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Beginners_guide/04_Loading_data.ipynb) as it forms part of the official DEA docs, and is a natural fit for that kind of information. Wiki is more agile and quick though, and is a good place for dumping useful info e.g. like Kirill's regular clarifications on `align`.

**Comment by robbibt** [comment]
Currently the `Loading data` notebook contains this info:

![image](https://user-images.githubusercontent.com/17680388/86982389-72b25380-c1cc-11ea-8a76-e11c2285dce2.png)

**Comment by robbibt** [comment]
`align` isn't even mentioned there at the moment, whoops. I think the problem is that that notebook loads Landsat geomedian data vs Landsat Collection 3... on one hand it makes for a nice simple example, but on the other hand it doesn't demonstrate why things like `groupby` and `align` are needed.

**Comment by robbibt** [comment]
Align is now covered here: https://docs.dea.ga.gov.au/notebooks/DEA_products/DEA_Landsat_Surface_Reflectance.html?highlight=align#Using-the-align-parameter-when-natively-loading-data
