### ISSUE TITLE
Write_cog needs some demo text

### ISSUE THREAD

**Issue by Gabzgit** [GeoscienceAustralia/dea-notebooks#606]
Since write_cog has replaced write_geotiff it would be handy to have some helpful text somewhere.

https://docs.dea.ga.gov.au/notebooks/Frequently_used_code/Exporting_GeoTIFFs.html seems like a good place to update, and other notebooks are now a little broken e.g. https://docs.dea.ga.gov.au/notebooks/Real_world_examples/Burnt_area_mapping.html

**Comment by robbibt** [comment]
Closing this in favour of #586
