### ISSUE TITLE
Update DEA Notebooks template and notebook headers to contain a direct Sandbox link 

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#618]
In meeting with Today regarding the new DEA website, it was suggested that we should include an easy link to every example notebook that will take users directly to the DEA Sandbox so they can run code interactively.

This would be easy to do by updating the DEA Notebooks header template, ideally via a bulk update:

https://www.internalpointers.com/post/linux-find-and-replace-text-multiple-files

**Comment by MatthewJA** [comment]
I think we can close this now, right @robbibt?

**Comment by robbibt** [comment]
Yep, closing
