### ISSUE TITLE
update technical info in https://docs.dea.ga.gov.au/ with data from https://cmi.ga.gov.au/data-products/dea 

### ISSUE THREAD

**Issue by juan-guerschman** [GeoscienceAustralia/dea-notebooks#620]
I was after some specific details on the nbar and nbart pipelines and methods in https://docs.dea.ga.gov.au/notebooks/DEA_datasets/Sentinel_2.html .
Simon Oliver pointed me to the very useful resource: https://cmi.ga.gov.au/data-products/dea/189/surface-reflectance-nbar-1-sentinel-2-msi and https://cmi.ga.gov.au/data-products/dea/190/surface-reflectance-nbart-1-sentinel-2-msi . They should be linked in docs.dea.gov.ga I think. 
Probably the same for all the other datasets:  https://cmi.ga.gov.au/data-products/dea

**Comment by CEKrause** [comment]
We face an issue where CMI links aren't persistent, so how can we link to them in things like this? It's a really good point, but I think we need to do some work with Simon's team on persistent IDs before we just copy links into the doco?

**Comment by robbibt** [comment]
Will be resolved by current CMI + User Guide work
