### ISSUE TITLE
"Compatibility" spelled incorrectly throughout repo

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#637]
Most notebooks have "compatibility" spelled incorrectly as "compatability" at the top.

**Comment by vaderjunior** [comment]
Hey,
I would like to do this.
Im new to all this so i dont understand what you meant by notebooks.
Could you explain?
thanks

**Comment by MatthewJA** [comment]
Jupyter notebooks are the main way we organise our code in this repo. Anything with a .ipynb extension, e.g. [this file](https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Frequently_used_code/Analyse_multiple_polygons.ipynb).

**Comment by MatthewJA** [comment]
If you haven't used notebooks before, perhaps this issue would be better for someone who has used them.

**Comment by sasthan** [comment]
Hi, I have experience with notebooks, and can fix the typo 'compatability'. Can I take this? If yes, in which repo should I be merging my PR?

**Comment by robbibt** [comment]
Hi @sasthan, we've just assigned this to @MatthewJA above. Thanks for the offer though!

**Comment by MatthewJA** [comment]
@robbibt Fixed the PR. Should be good for review now.

**Comment by robbibt** [comment]
Closed by #638
