### ISSUE TITLE
Broken formatting for Polygonising pixel edges notebook header

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#647]
In user guide: https://docs.dea.ga.gov.au/notebooks/Frequently_used_code/Polygonise_pixel_edges.html

![image](https://user-images.githubusercontent.com/17680388/96518336-699a4d80-12b6-11eb-923c-edff6c69543c.png)

Perhaps the header text was copied incorrectly somehow? Could try restoring directly from the notebooks template

**Comment by BexDunn** [comment]
fixed by #648
