### ISSUE TITLE
Improve the error message for `mostcommon_crs` when no data are found

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#659]
Current error message:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-309-11179f414b29> in <module>
      4 #                             'crs': 'EPSG:3577',
      5                             'x': xlim,
----> 6                             'y': ylim})

~/dea-notebooks/Scripts/dea_datahandling.py in mostcommon_crs(dc, product, query)
    531     # Identify most common CRS
    532     crs_counts = Counter(crs_list)
--> 533     crs_mostcommon = crs_counts.most_common(1)[0][0]
    534 
    535     # Warn user if multiple CRSs are encountered

IndexError: list index out of range
```

**Comment by robbibt** [comment]
Yep, returning `None` could work. The workflow where this error occurs is often when someone e.g. passes a Landsat 5 time range while still specifying Landsat 8 as the product etc, which then results in no results. A simple error message explaining this and nudging the user to select a more relevant product would help.

**Comment by MatthewJA** [comment]
Another thing that can happen is you simply have no data in the time period, which is what I encountered it with

**Comment by robbibt** [comment]
I might fix this this week - to clarify, I think that's the same issue as above: choosing a time period (e.g. 1990) where the specified product (e.g. Landsat 8) has no data?

**Comment by MatthewJA** [comment]
Yep
