### ISSUE TITLE
"Parallel processing with Dask" notebook currently missing from user guide

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#661]
The [`09_Parallel_processing_with_Dask.ipynb` notebook](https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Beginners_guide/09_Parallel_processing_with_Dask.ipynb) has gone missing from the User Guide:

![image](https://user-images.githubusercontent.com/17680388/97254456-814b7600-1862-11eb-9d66-0e256dd61645.png)

This seems to be because the Readme uses the wrong capitalisation. The wrong capitalisation also appears to be used in these sections, meaning the links in the Beginner's guides currently don't work.

This can be fixed by updating the Readme and links to this notebook within each Beginner's guide notebook.

**Comment by BexDunn** [comment]
Fixed, and the docs have been rebuilt :) 
![image](https://user-images.githubusercontent.com/20038594/98049932-cbe17980-1e84-11eb-86b8-74de1c770aa0.png)
