### ISSUE TITLE
Update GDAL imports to new format

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#701]
Old format is:

>>> import gdal
>>> import ogr
>>> import osr
>>> import gdalnumeric
>>> import gdalconst

New format is:

>>> from osgeo import gdal
>>> from osgeo import ogr
>>> from osgeo import osr
>>> from osgeo import gdal_array
>>> from osgeo import gdalconst

**Comment by robbibt** [comment]
Done in the latest PR
