### ISSUE TITLE
"OperationalError: fe_sendauth: no password supplied" error when connecting to DEA datacube on NCI

### ISSUE THREAD

**Issue by shuangliu2023** [GeoscienceAustralia/dea-notebooks#703]
I followed the examples on DEA website and try to run them on both NCI and DEA Sandbox, and it shows 'OperationalError: fe_sendauth: no password supplied' when I run the code `dc=datacube.Datacube(app='Chlorophhyll-monitoring')` on both of them. I also tried other examples and this error also happened. How can I solve this problem? Thanks!

**Comment by robbibt** [comment]
Hey @rtyme! Do you receive that message when you run the notebook on the DEA Sandbox, or just the NCI? I've just tested it on the Sandbox and didn't get that message - I can't see any way it would happen on the Sandbox, but on the NCI it sounds like it might be an issue related to a .pgpass file. 

@eloise-b, does that sound right to you, and do you have any advice for how to address .pgpass isses?

**Comment by robbibt** [comment]
@rtyme I think this will solve your problem: open a terminal ("System Tools >Terminal") and run this command, then restart Jupyter:
```
cp ~/old_vdi_home/.pgpass .pgpass
```

**Comment by robbibt** [comment]
Hey @rtyme , I'm going to close this for now - please leave a comment if the solution above didn't help and we can have another look at this issue!
