### ISSUE TITLE
Create coastal masking `Frequently_used` notebook

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#707]
We get a query on Slack about creating a coastal mask roughly every month or so. It would be great to have a `Frequently_used_code` notebook that demonstrates several different approaches to this, including: 

- Rasterize the 1:100,000 shapefile coastline here: g/data/r78/rt1527/shapefiles/australia/australia/cstauscd_r.shp  It's pretty low res, but can be good when you just need a really simple approximate coastline for the entire country
- dc.load the ITEM dataset, and then extract the ITEM.relative == 0  tidal interval. This will get you a 30m res version if the coastline, but will probably need some cleaning to remove inland water that isn't intertidal. (you can try removing inland waterbodies by size or connectivity to the ocean to clean them up)

**Comment by MatthewJA** [comment]
We do sort of have one, here: https://docs.dea.ga.gov.au/notebooks/Scientific_workflows/DEAWaterbodies/DEAWaterbodiesSupplement/CreateAustralianCoastlineUsingITEM.html

**Comment by robbibt** [comment]
May revisit once DEA Intertidal suite is ready
