### ISSUE TITLE
Speed up xr_vectorize

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#710]
`dea_spatialtools.xr_vectorize` is seemingly orders of magnitude slower than `dea_spatialtools.subpixel_contours`, despite both kind of doing the same thing. I suspect this is the call to gdal/rasterio, which we can probably replace with `skimage.measure.label`.

**Comment by uchchwhash** [comment]
Do they return the same type of objects though?

**Comment by MatthewJA** [comment]
No, but I have postprocessing code on the `subpixel_contours` to get them in the same format, and it's not the bottleneck as far as I can tell
