### ISSUE TITLE
Fix read-the-docs formatting of Sandbox access link

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#723]
Because Sphinx/readthedocs is excessively picky and can't handle more than one type of formatting at once, the current bold and hyperlinked code in the header of our notebooks renders incorrectly on the DEA User Guide (even though it works fine on Github): 

![image](https://user-images.githubusercontent.com/17680388/100184342-69d0dd00-2f35-11eb-976d-d5449a051abc.png)
https://docs.dea.ga.gov.au/notebooks/Frequently_used_code/Detecting_seasonality.html

We should replace this text:

`[**Sign up to the DEA Sandbox**](https://docs.dea.ga.gov.au/setup/sandbox.html) to run this notebook interactively from a browser`

With something like:

`**DEA Sandbox:** [Sign up to the DEA Sandbox to run this notebook interactively from a browser](https://docs.dea.ga.gov.au/setup/sandbox.html)`

**Comment by MatthewJA** [comment]
Does it work if you swap the order of operations? i.e.

`**[Sign up to the DEA Sandbox](https://docs.dea.ga.gov.au/setup/sandbox.html)** to run this notebook interactively from a browser`

**Comment by robbibt** [comment]
Let's test it! https://github.com/GeoscienceAustralia/dea-notebooks/pull/725

**Comment by robbibt** [comment]
Unfortunately not: 
![image](https://user-images.githubusercontent.com/17680388/100189500-8aeafb00-2f40-11eb-99ef-5502605a4e87.png)

It looks like the notebooks get converted to reStructuredText by readthedocs, and that doesn't support nested formatting :( 
https://stackoverflow.com/a/11984833/2510900

**Comment by robbibt** [comment]
Seems to be fixed: 
![image](https://user-images.githubusercontent.com/17680388/125021087-5259f500-e0bd-11eb-86ed-a3387d1bf8ee.png)
