### ISSUE TITLE
Broken `on_hover` functionality in `map_shapefile` function of `dea_plotting.py`

### ISSUE THREAD

**Issue by erialC-P** [GeoscienceAustralia/dea-notebooks#741]
`on_hover` functionality in `map_shapefile` function of `dea_plotting.py` reportedly broken for a wide range of users (myself included). A work around solution, based on the following code snippet, could be incorporated (courtesy of the widgets tutorial in the Scipy 2020 tutorial set - https://www.scipy2020.scipy.org/tutorial-information)

`from ipywidgets import Text, HTML, HBox
from ipyleaflet import GeoJSON, WidgetControl, Map 
import json
m = Map(center = (43,-100), zoom = 4)
##  Plot the data
geo_json_data = json.load(open('us-states-density-colored.json'))
geojson = GeoJSON(data=geo_json_data, hover_style={'color': 'black', 'dashArray': '5, 5', 'weight': 2})
m.add_layer(geojson)
##  Plot a text box
html = HTML('''
    <h4>US population density</h4>
    Hover over a state
''')
html.layout.margin = '0px 20px 20px 20px'
control = WidgetControl(widget=html, position='topright')
m.add_control(control)
##  Function to update the text box
def update_html(properties, **kwargs):
    html.value = '''
        <h4>US population density</h4>
        <h2><b>{}</b></h2>
        {} people / mi^2
    '''.format(properties['name'], properties['density'])
##  Attach the hover and text update functionality to the data layer
geojson.on_hover(update_html)
##  Plot all on a map
m`

**Comment by robbibt** [comment]
Map shapefile func is no longer in the repo
