### ISSUE TITLE
Add legend to `map_shapefile` function of `dea_plotting.py`

### ISSUE THREAD

**Issue by erialC-P** [GeoscienceAustralia/dea-notebooks#742]
I added a handy legend to the `map_shapefile` function in `dea_plotting.py` and thought it could be a useful addition to the repo

`# Set the legend conditions and round to 2 decimal places

    if continuous:

        legend = LegendControl({np.around(np.quantile(classes, 0.00),2): colormap.rgb_hex_str(0.00),
                                np.around(np.quantile(classes, 0.25),2): colormap.rgb_hex_str(0.25),
                                np.around(np.quantile(classes, 0.50),2): colormap.rgb_hex_str(0.50),
                                np.around(np.quantile(classes, 0.75),2): colormap.rgb_hex_str(0.75),
                                np.around(np.quantile(classes, 1.00),2): colormap.rgb_hex_str(1.00) }, 
                               name=attribute, position="bottomleft")

        m.add_control(legend)`

**Comment by robbibt** [comment]
Superceded by the `.explore()` functionality in geopandas
