### ISSUE TITLE
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [GeoscienceAustralia/dea-notebooks#747]
Hi, I was running the "Estimate Climate Driver Influence on Rainfall" notebook and it seems like the base map package has not been proper installed in the system. Please help double-check.
Thanks,
Daniel

**Comment by robbibt** [comment]
Hey @Daniel-Trung-Nguyen , thanks for the report! What environment were you using when you got this issue? The NCI/VDI or DEA Sandbox? @MatthewJA wrote this notebook, so might have some thoughts on why it doesn't work depending on the environment.

**Comment by Daniel-Trung-Nguyen** [comment]
Hi @robbibt and @MatthewJA,
I got this issue on the DEA Sandbox. The "import mpl_toolkits.basemap" loaded successfully with no issues on the NCI environment.
Cheers,
Daniel

**Comment by MatthewJA** [comment]
This notebook will only work on the NCI - the data aren't available on Sandbox.

**Comment by MatthewJA** [comment]
Looks like that notebook needs updating anyway to use cartopy.
