### ISSUE TITLE
Increase storage on Sandbox

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [GeoscienceAustralia/dea-notebooks#754]
Hi,
DEA Sandbox only provides ~10GB of storage under /home/jovyan. I wonder if there is a way to increase the quota? I am running an analysis and need a little more storage.
Thanks,
Daniel

**Comment by robbibt** [comment]
Hey Daniel, unfortunately at this stage it isn't possible to increase quotas on the Sandbox - your best bet might be to process your work in batches to free up space as you go. I've also left a comment on your other NCI/VDI issue which will hopefully help a little.
