### ISSUE TITLE
Update load_ard to load and cloud mask Collection 3 Fractional Cover (ga_ls_fc_3)

### ISSUE THREAD

**Issue by juan-guerschman** [GeoscienceAustralia/dea-notebooks#762]
@robbibt

**Comment by robbibt** [comment]
This used to be possible for Collection 2 data using `load_clearlandsat`. To get the same functionality in `load_ard`, the challenge will be using the cloud mask from the multiple Landsat products (e.g. 'ga_ls5t_ard_3', 'ga_ls7e_ard_3', 'ga_ls8c_ard_3`) to mask the single Collection 3 Fractional Cover product.

**Comment by juan-guerschman** [comment]
isn't the cloud info included in ga_ls_wo_3?  In that case, read also ga_ls_wo_3  and use those masks?

**Comment by robbibt** [comment]
Integrating FC and WO masking into `load_ard` is more complicated than expected; closing this issue to raise future issues to create dedicated WO/FC cloud masking functions
