### ISSUE TITLE
List who is using and citing our work! (list of papers and/or projects)

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#768]
Like hypothesis does :) 
https://hypothesis.readthedocs.io/en/latest/usage.html

* Short, M.A., Norman, R.S., Pillans, B., De Deckker, P., Usback, R., Opdyke, B.N., Ransley, T.R., Gray, S. and McPhail, D.C., 2020. Two centuries of water-level records at Lake George, NSW. Australian Journal of Earth Sciences, pp.1-20.
https://www.tandfonline.com/doi/pdf/10.1080/08120099.2020.1821247

* Bishop-Taylor, R., Sagar, S., Lymburner, L., Alam, I. and Sixsmith, J., 2019. Sub-pixel waterline extraction: Characterising accuracy and sensitivity to indices and spectra. Remote Sensing, 11(24), p.2984.
https://www.mdpi.com/2072-4292/11/24/2984

* Abhik, S., Hope, P., Hendon, H.H., Hutley, L.B., Johnson, S., Drosdowsky, W. and Brown, J., 2021. The Influence of 2015-16 El Niño On the Record-Breaking Mangrove Dieback Along Northern Australia Coast. Scientific Reports, Preprint.
https://doi.org/10.21203/rs.3.rs-650667/v1

**Comment by robbibt** [comment]
Done!
