### ISSUE TITLE
Implement a set of tests with dea-sandbox docker container to ensure stable environment

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-notebooks#770]
The [dea-sandbox](https://github.com/GeoscienceAustralia/dea-sandbox) docker container is a complex beast with with lots of python modules whose dependency graph was recently captured [here](https://whatnick.github.io/python-depviz/index.html), this may have changed since.

Implement a [pytest-notebooks](https://pypi.org/project/pytest-notebook/) based test harness to render all the notebooks in a datacube accessible environment, perhaps [dea-airflow](https://github.com/GeoscienceAustralia/dea-airflow) to run through all fully automatic notebooks and ensure the built environment is consistent.

**Comment by robbibt** [comment]
We have this now!
