### ISSUE TITLE
Referencing in dea-notebooks

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#80]
Further to discussions today about making sure we reference any direct quotes from previously published material:

I've added a section in dea-notebooks documentation with a link to the GA referencing guide.

We need to please caption and reference any images used that have been previously published elsewhere.

For document references,
I've decided to include an internal and and external link for the first reference to any externally published content, followed by internal links for further references. These internal links go to a references cell at the end of the notebook, where references are formatted according to the GA style guide (now linked to in the dea notebooks getting started guide, or at <http://www.ga.gov.au/copyright/how-to-cite-geoscience-australia-source-of-information> )

Thoughts on this are requested - maybe there is a better way? I know it's hard to use internal links on github, but the external links work really well.

This is necessary if you have notebooks that consistently use directly copied and pasted information from elsewhere. Please don't use anything copied-and-pasted without enclosing it in quotes and referencing, as per usual scientific publication standards, particularly as these GA- published notebooks are within GeoscienceAustralia's repository and visible to external collaborators. 

If you are able to, you can paraphrase external sources but please include a reference if you do so.

Please can we check any published notebooks for these issues.

Regards,
Bex

**Comment by robbibt** [comment]
I definitely agree with referencing anything (images or text) that's been lifted from other sources... so far I've been dealing with it simply by hyperlinking in-text references, although this doesn't apply to internal links (by this do you mean GA TRIM links?). The biggest issue I can see is that since notebooks are a pretty visual medium we don't want to add in too much clutter or they will become hard to read.

**Comment by robbibt** [comment]
Mentioned in the overall readme; can close
