### ISSUE TITLE
Replace Scripts with Tools

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#849]
Not using an actual install (which wouldn't work on the NCI), but instead:

```python
import sys
sys.path.insert(1, '../Scripts')
import dea_spatialtools
```
would become
```python
import sys
sys.path.insert(1, '../Tools')
import dea_tools.spatial
```

We also need to move auxiliary scripts to the extra data folder. We can then delete Scripts.

**Comment by MatthewJA** [comment]
Ping @robbibt @BexDunn @s-m-t-c for visibility

**Comment by robbibt** [comment]
This will be a reasonably large job, so we might want to divide labour a little (e.g. we could allocate `Beginners_guide`, `Frequenty_used_code`, `Real_world_examples` to different people etc

Should also note here that this is ideally a short term fix - in the longer run it would be much preferable to import directly from the installed module. We just need a solution for that on the NCI first while we still support that environment

**Comment by robbibt** [comment]
Relevant to #731 and #732

**Comment by MatthewJA** [comment]
Agreed on both

**Comment by MatthewJA** [comment]
Now that we're on PyPI, maybe we can get dea-tools==latest installed on the Sandbox? That'd make this easier.

**Comment by MatthewJA** [comment]
(whoops)
