### ISSUE TITLE
Update the dea-tools documentation with pip

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#861]
Current installation details are out-of-date; these should be updated once we're happy with the PyPI release process.

**Comment by robbibt** [comment]
Yep, fantastic. We can also add in a bit of a larger blurb about what `dea-tools` is/does, and a summary of some of its main features up the top:

![image](https://user-images.githubusercontent.com/17680388/131931920-e5ad65c6-ff5c-4387-bbb4-c028c9aad25b.png)

**Comment by MatthewJA** [comment]
That sounds good!

**Comment by robbibt** [comment]
Done
