### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by leaf0917** [GeoscienceAustralia/dea-notebooks#871]
When I import packages below:

import datacube
import pandas as pd
from odc.ui import DcViewer

Set some configurations for displaying tables nicely
pd.set_option('display.max_colwidth', 200)
pd.set_option('display.max_rows', None)

then report error:

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_21316/3410133711.py in <module>
      1 import datacube
      2 import pandas as pd
----> 3 from odc.ui import DcViewer
      4 
      5 # Set some configurations for displaying tables nicely

ModuleNotFoundError: No module named 'odc'

**Comment by robbibt** [comment]
Hi @leaf0917, where are you running this code? On the DEA Sandbox? I've just tried running this notebook that uses the code you posted above and so far it seems to be working as intended:

https://docs.dea.ga.gov.au/notebooks/Beginners_guide/03_Products_and_measurements.html

**Comment by leaf0917** [comment]
> Hi @leaf0917, where are you running this code? On the DEA Sandbox? I've just tried running this notebook that uses the code you posted above and so far it seems to be working as intended:
> 
> https://docs.dea.ga.gov.au/notebooks/Beginners_guide/03_Products_and_measurements.html

I just download it and run the \Beginners_guidefile\03_Products_and_measurements.ipynb in jupyter notebook
