### ISSUE TITLE
Replace print statements in bandindices  with logging or warning statements

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#891]
**Describe the bug/issue**
In the band_indices function, the default behaviour is to print out which bands we are dropping. This breaks when the function is run non-interactively e.g. running in conflux. 

 `if drop:
        bands_to_drop=list(ds.data_vars)
        print(f'Dropping bands {bands_to_drop}')`

**Steps to reproduce**
Run band indices code non-interactively

**Expected behaviour**
Code should use warnings or logging instead to say which bands are dropped

**Environment information**
dea-conflux

**Comment by robbibt** [comment]
Interesting! Do print statements really break things like conflux? I have mixed feelings about functions that produce lots of warnings - it often creates a lot of visual clutter and can scare users into thinking their code has broken (e.g. pretty common for new users to confuse a warning for an error message). In this case the "Dropping bands" message isn't so much a warning, but a bit of extra context to help users understand their outputs... Could we instead add something like a "verbose" param that could be set to False to hide prints when running non-interactively?

**Comment by BexDunn** [comment]
we could use logging.info for example instead? Then it's an INFO: not an ERROR or WARNING

This would allow us to set logging levels e.g. info/warning/debug/error/critical

I could be wrong, but I'm pretty sure print prints to stdout and when there is none it can cause errors.

**Comment by BexDunn** [comment]
Hey, this one is no longer an issue for the conflux use case. Thanks team.

**Comment by BexDunn** [comment]
Closing as per comment above.
