### ISSUE TITLE
DEA WIT doesn't have an intro notebook

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-notebooks#902]
No `DEA datasets` notebook for intro to WIT that can be linked off the web page.

**Comment by BexDunn** [comment]
Sai and I are working on this :D

**Comment by BexDunn** [comment]
@LaurenSchenk1 and I are working on this - this is in progress :)

**Comment by robbibt** [comment]
@BexDunn Looks like we can close this one now!

**Comment by BexDunn** [comment]
Closed by PR #1102 :)
