### ISSUE TITLE
Update three_band_image_subplots function to work identically to three_band_image

### ISSUE THREAD

**Issue by asivapra** [GeoscienceAustralia/dea-notebooks#92]
Robbi,
In the "DEAPlotting.three_band_image_subplots", could you consider changing the following line?

img_toshow = rawimg / 5000
to
img_toshow = (rawimg / 5000).clip(0, 1)

It will avoid warnings like below.

"Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers)."

**Comment by robbibt** [comment]
I have renamed this issue as the three_band_image_subplots really should be updated to function exactly the same as the three_band_image function. This will probably break people's code, so will think on how to do this the best way.
