### ISSUE TITLE
cannot import name 'write_geotiff' from'datacube.helpers'

### ISSUE THREAD

**Issue by ErinKenna** [GeoscienceAustralia/dea-notebooks#929]
https://github.com/GeoscienceAustralia/dea-notebooks/blob/654b252a809f15c89ef6a8f3b2cfb69ca743903a/Tools/dea_tools/spatial.py#L48  

**Describe the bug/issue**  
Import of `dea_tools.spatial` raises "ImportError: cannot import name 'write_geotiff' from'datacube.helpers'".  
Error introduced by recent [commit](https://github.com/opendatacube/datacube-core/commit/c84da04e0a81a32d269c1bece19ae649d11b2d44) in datacube-core/develop.  

**Steps to reproduce**  
1. `from dea_tools.classification import predict_xr`  

**Expected behaviour**
Module should load without ImportError.  

**Environment information**
[CSIRO EASI](https://hub.csiro.easi-eo.solutions/) using Datacube package 1.8.7.dev0

**Comment by ErinKenna** [comment]
Added PR: https://github.com/GeoscienceAustralia/dea-notebooks/pull/930

**Comment by robbibt** [comment]
Closed in #930
