### ISSUE TITLE
Database layout version error

### ISSUE THREAD

**Issue by Pkandel11** [GeoscienceAustralia/dea-notebooks#945]
I get this error when I am trying to use dea_tools. I tried to unset pro_lib environment but nothing changed. Could anyone help me with this?
<img width="675" alt="Screen Shot 2022-08-23 at 2 02 52 PM" src="https://user-images.githubusercontent.com/91206640/186239368-6cc5255a-d70a-4da5-8ea3-5210be079686.png">
**Describe the bug/issue**
A clear and concise description of what the bug/issue is, including screenshots if relevant. 

**Steps to reproduce**
Steps to reproduce the behaviour. For example:
1. Open DEA Sandbox
2. Launch the "Beginners_guide/01_Jupyter_notebooks.ipynb" notebook
3. Run all cells
4. Code in section "X" produces error "XYZ"

**Expected behaviour**

**Environment information**
What datacube environment are you using? i.e. [DEA Sandbox](https://docs.dea.ga.gov.au/setup/sandbox.html) or the [NCI (Gadi or VDI)](https://docs.dea.ga.gov.au/setup/NCI/README.html)

**Comment by robbibt** [comment]
Hi @Pkandel11! Thanks for this - Can I ask where you're running this code? Is it on the DEA Sandbox?

**Comment by robbibt** [comment]
I think this has been fixed by recent updates to the DEA Sandbox images
