### ISSUE TITLE
Add how to review a pull request section to wiki

### ISSUE THREAD

**Issue by margaretharrison** [GeoscienceAustralia/dea-notebooks#959]
The current guide to using git doesn't include instructions on how to review a pull request. We should add it. 

https://github.com/GeoscienceAustralia/dea-notebooks/wiki/Guide-to-using-DEA-Notebooks-with-git

**Comment by LaurenSchenk1** [comment]
Fixed
https://github.com/GeoscienceAustralia/dea-notebooks/wiki/Guide-to-using-DEA-Notebooks-with-git#reviewing-and-approving-a-pull-request
