### ISSUE TITLE
problem with plot land cover tool

### ISSUE THREAD

**Issue by Kooie-cate** [GeoscienceAustralia/dea-notebooks#975]
**Describe the bug/issue**
A clear and concise description of what the bug/issue is, including screenshots if relevant. 

**Steps to reproduce**
Steps to reproduce the behaviour. For example:
1. Open DEA Sandbox
2. Launch the "DEA_datasetsDEA_land_cover.ipynb" notebook
3. change time range in cell 4 to be a single year
4. Run all cells except skip cell 10
5. Code in section "11" produces error "AttributeError: 'AxesSubplot' object has no attribute 'flat'"

**Expected behaviour**
I would expect a single temporal layer to simply plot the same as it does when the "year" variable is given. the code is trying to generate a plot with multiple subplots then breaking when trying to fit a colour bar to one of those subplots.

**Environment information**
[DEA Sandbox]

**Comment by robbibt** [comment]
Closed by #1095
