### ISSUE TITLE
Update at least some Sentinel-2 Collection 3 notebooks to use cloud masking from `s2cloudless`

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#980]
We should update this repository to include at least some nice examples of applying cloud masking using the new `s2cloudless_mask` band. This will provide users with code to get started with this new cloud mask.

An optional extra could be a simple notebook in `Frequently_used_code` that shows how to load and manipulate the quantitative `s2cloudless_prob` cloud probability layer (and any cool application of using it that we can think up)

**Comment by geoscience-aman** [comment]
Application of `s2cloudless_mask` covered in PR #983
Usage of `s2cloudless` with `load_ard()` covered in PR #984

Closing as duplicate.
