### ISSUE TITLE
Update tide modelling functions to use refactored version 2.0 of `pyTMD`

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#989]
https://github.com/tsutterley/pyTMD/releases/tag/2.0.0

**Comment by 2320sharon** [comment]
Hi @robbibt 
Thank you for all your hard work on the dea_notebooks and dea_tools package. I see you're planning on updating to pyTMD version 2. We are working on a package that might use the dea_tools package to tidally correct satellite imagery and I was wondering what your estimated time frame was on updating to version 2 of pyTMD?

**Comment by robbibt** [comment]
Hey @2320sharon! I'll look into it this week and get a better idea of how complex this will be - I don't anticipate it will be too tricky. We're actually hoping to release the first official version 1.0.0 of `dea_tools` over the next week or so, so I'll see if we can get the pyTMD update into that release. 

Either way though, we'll aim to make the update in a backwards-compatible way, so I don't think the switch to pyTMD 2.0 should change much about how the tide modelling funcs in `dea_tools` behave, so you can probably use one of the [latest versions here](https://pypi.org/project/dea-tools/#history) for now without much issue. The pyTMD 2.0 updates may make things a bit more efficient to run, but so far the biggest impact on performance we've found is to clip the FES2014 tidal consituent NetCDFs to a bounding box around your study area (e.g. we clip them to Australia) rather than use the global NetCDFs out of the box (we've found it can reduce the time to load those consituents in pyTMD from minutes to just a few seconds). 😃

**Comment by 2320sharon** [comment]
Thank you for taking the time to dig into this issue this week and for responding so quickly. It's great news to hear that the first official release of `dea_tools` is almost ready to go, and it's perfectly timed!💯 

 I also appreciate your clarification that the new version of dea_tools will likely be backwards compatible. Initially, I was concerned that the significant differences in the code structure between `pyTMD 1.1.3` and `pyTMD 2.0.0` would require substantial modifications to `dea_tools`. I'm planning to investigate  the [latest versions here](https://pypi.org/project/dea-tools/#history) of the code and see it will work for our use case.

**Comment by robbibt** [comment]
@2320sharon Would very much welcome any feedback - our tools have been developed primary for our [DEA Coastlines](https://maps.dea.ga.gov.au/story/DEACoastlines) use case, but theoretically they should be useful for any application that combines satellite imagery with tide modelling. We just might need to tweak some things to make them as generalisable as possible in case there's any Australia-specific assumptions built in! 😃 

I'll reach out to the author of pyTMD this week and see if I can get a better idea of what needs to be done to update to 2.0.0.

**Comment by 2320sharon** [comment]
Sounds good, I'll share any feedback our team has. Thanks again for working on this

**Comment by robbibt** [comment]
Done in #1077
